language: node_js
node_js:
  - 8
sudo: required
services: 
  - docker

before_install: 
  - docker build -t shreykejriwal/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true shreykejriwal/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket: "elasticbeanstalk-us-east-1-752176845457"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

