language: node_js
sudo: required
services: 
  - docker

before_install: 
  - docker build -t shreykejriwal/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true shreykejriwal/docker-react npm run test